version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.5.1-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/activity-tracker
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/activity-tracker

  bundle_dependencies:
    docker:
      - image: circleci/ruby:2.5.1-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/activity-tracker
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/activity-tracker/vendor/bundle

  rake_test:
    docker:
      - image: circleci/ruby:2.5.1-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:9.4.12-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: activity_tracker_test 
    working_directory: ~/activity-tracker
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle --path vendor/bundle
      - run: bundle exec rake db:migrate
      - run:
          name: Run tests
          command: bin/rails test
  deploy:
    machine:
        enabled: true
    working_directory: ~/activity-tracker
    environment:
      - HEROKU_APP: fierce-retreat-90493
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          key: v1-assets-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master --force
      - run:
          name: setup Heroku
          command: bash .circleci/setup-heroku.sh
      - run:
          name: DB Migration
          command: |
            heroku run rake db:migrate --app $HEROKU_APP

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - rake_test:
          requires:
            - bundle_dependencies
      - deploy:
          requires:
            - rake_test